### PR TITLE
Seed data based on new CSVs

### LINKED ISSUE #136: Seed data will need to be made aware of the new Building model
### User story
As a developer, when I run `db:seed`, and all the admin users and lockers are created with the correct `building_id` values in the database.

### Current status

The `space_admins.csv` and `spaces.csv` files don't even have a column for the building yet.

Possibly related to #116, in that this ticket is also about seeding lockers.

### PR DESCRIPTION
**Pull request by maxkadel**
- Generate CSVs from which to seed the databases
- This will allow us to periodically update seed CSVs from production (right now we do not have a way to re-create the old csvs)
- The new seeds will be aware of buildings
- The new seed process is much faster

Closes #136

### CODE REVIEW

**Comment by maxkadel** [comment]
This is on staging and I created the CSV files there. You can try it on your local environment by pulling down this branch, then

```bash
 scp deploy@lockers-and-study-spaces-staging1.princeton.edu:\*.csv .
```

then following the seeding steps in the readme.

**Review by sandbergja — CHANGES_REQUESTED** [review]
Thanks, @maxkadel !  This worked well for me.  I had two thoughts:

1. `rake csv:all` adds a lot of files to the `current` directory.  We can always move them out manually after running the task, but I thought it would be nicer to default to writing them to the home directory (where they would typically be used), or at least allowing us to pass a directory as a configuration option.
2. Could you add some documentation to the README about how to refresh the CSVs?

**Review by kevinreiss — APPROVED** [review]

**Review by kevinreiss — COMMENTED** [review]
Other than Jane's suggestions this looks good to me.

**Review by sandbergja — APPROVED** [review]
Thanks, @maxkadel !

**Pull request merged**
