### PR TITLE
Locker release

### LINKED ISSUE #68: Expiration Date should be set to Release Date
There seems to be a bug in the system.  If the expiration date is not set on release the lockers still show up in reports.

Simple fix could be setting the expiration date to the release date on release.  Could also check for released in report.

From April
```
The last thing is when I release a locker, it stays in the active assignments list unless I change the expiration date so that the locker is expired. I don’t mind doing this and maybe I need to retrain myself to make sure to change the expiration date especially if this is the easiest solution. It throws off the statistics somehow if I don’t. When I run the two reports at the end of the month, the number of lockers by department and the number of lockers by floor are not the same.
```

### PR DESCRIPTION
**Pull request by leefaisonr**
closes #68

### CODE REVIEW

**Review by christinach — CHANGES_REQUESTED** [review]
@leefaisonr thank you for working on this issue!! It's a good practice to include in the commit  a Co-authored-by when we collaborate with someone else. You can find @sandbergja's info in this message https://github.com/pulibrary/pul-it-handbook/blob/main/gitmessage.md.

**Comment by christinach** [comment]
@leefaisonr @sandbergja can you also squash the commits ? some of them are not part of the end result.

**Comment by leefaisonr** [comment]
Hi @christinach , please review the changes and let us know if anything else is needed :) thanks!

**Review by christinach — COMMENTED** [review]
@leefaisonr @sandbergja one more question. Why are you setting the locker expiration date to be the previous date of the release and you don't set it to be the same date as the  release date? 
In the issue comment April mentioned that she runs some kind of statistics at the end of the month.  Hypothetically speaking if the expiration date of some lockers is at the end of the month the statistics will still be off because the release date will be one day before.

**Comment by christinach** [comment]
Can you please add two empty line after the Co-authored-by. That way github reads the Co-author , otherwise it's only text. see https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Review by christinach — APPROVED** [review]
@leefaisonr @sandbergja Thank you!

**Pull request merged**
